# SITE CONFIGURATION
baseurl: ""
url: "https://keepintouchfm.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Keep in Touch
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Keep in Touch podcast with Nick and Todd" # used by search engines

  # Header and footer text
  header_text: >
     <p>Two geeky dads, Google Developer Group leads, dog owners, and tech enthusiasts keep in touch in spite of being in different hemispheres and a ridiculous number of time zones apart. Todd is a GDG Lead in USA, and Nick is GDG Lead in New Zealand. After meeting at Google I/O they decided to keep in touch and these are their ramblings about all things Apple, Google, neat tech, kids, family, dogs, and whatever else goes through their heads...</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with a <a href="https://github.com/keepintouchfm/keepintouchfm.github.io">Keep in Touch fork of the Type Theme</a>

  # Icons
  rss: true
  email_address: keepintouchfm@gmai.com # Full email address, e.g. "sam@example.com"
  podcast: "https://anchor.fm/keep-in-touch"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "keepintouchfm"
  gitter:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "nicktmro"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_podcast: "Listen on"
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
